### ISSUE TITLE
Support "remote"-entities

### ISSUE THREAD

**Issue by pri-me** [unfoldedcircle/integration-home-assistant#23] opened 2023-09-24 18:06 UTC
The "Remotes" section in the web configurator currently supports only IR-remotes. 

This is a request for it to also support the HA "remote" enitity exposed by some integrations (e.g. `remote.philips_tv`).

Currently, it is necessary to create a script for each button in order to use the remote via HA. This is not only tedious to create but also problematic since an activity only allows 50 active entities and each press is an entity. 

With remote entity support, you would just add the remote entity and thus expose all commands to Remote Two like with IR remotes.

**Comment by DavidSpek** [comment] 2023-10-11 13:28
This code comment seems somewhat related: https://github.com/unfoldedcircle/integration-home-assistant/blob/47903d484d09ee0f9534caaf553dfd625d06b2b7/src/client/service/media_player.rs#L87C44-L87C44

**Comment by mvdwetering** [comment] 2023-12-12 19:47
This would be cool, but not sure how UC would get to know about the supported commands for that specific Remote entity. Unfortunately  HA has no mechanism to indicate which commands are supported.

There was an architectural discussion about something like this, but that seems to have died out https://github.com/home-assistant/architecture/discussions/875

**Comment by albaintor** [comment] 2024-01-13 13:26
> This would be cool, but not sure how UC would get to know about the supported commands for that specific Remote entity. Unfortunately HA has no mechanism to indicate which commands are supported.
> 
> There was an architectural discussion about something like this, but that seems to have died out [home-assistant/architecture#875](https://github.com/home-assistant/architecture/discussions/875)
> 
> Edit: that being said, just having a textbox or something where we could just copy-paste the supported commands from the Home Assistant documentation would be a great help.

Hi, sure but one could be the same behaviour as the "send command" function where you type the corresponding command in plain text.
Actually this is a big limitation because the media player component has limited functions (play/pause, next/previous) and not the additional commands (such as arrow keys/OK commands).
Thank you

**Comment by zehnm** [comment] 2024-01-18 09:47
To integrate HA remote-entites requires support in the integration API, core services and web-configurator. They don't fully match the current internal IR remote-entity and will require additional logic in the core services. If they currently slip through as available entities, then this is a bug and not a feature :-)
Only the [documented entities in the Core-Api](https://github.com/unfoldedcircle/core-api/tree/main/doc/entities) are supported.

Supporting more HA entities, including remotes, is planned though.

**Comment by antifuchs** [comment] 2024-02-17 18:26
I've worked around this limitation in a slightly annoying way, which nevertheless seems to work a bit better than the built-in appletv remote for e.g. play/pause buttons on the remote UI (e.g. https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/315). Here's what I did:

1. Make one button helper entity per button on the appletv remote. Name them `Home Theater Remote -  <command>` This is annoying to do, but you only have do it once. I don't think there's a way to export the yaml for the buttons I created, otherwise I'd paste it here to ease your suffering.
2. Make an automation that hooks the appletv remote entity up to each of those buttons:
  ```yaml
id: '1708186917053'
alias: Translate AppleTV buttons to remote events
description: ''
trigger:
  - platform: state
    entity_id:
      - input_button.home_theater_cursor_up
      - input_button.home_theater_cursor_down
      - input_button.home_theater_cursor_left
      - input_button.home_theater_cursor_right
      - input_button.home_theater_ok
      - input_button.home_theater_remote_menu
      - input_button.home_theater_remote_turn_off
      - input_button.home_theater_remote_turn_on
      - input_button.home_theater_remote_play_pause
      - input_button.home_theater_remote_home
      - input_button.home_theater_remote_volume_down
      - input_button.home_theater_remote_volume_up
      - input_button.home_theater_remote_channel_down
      - input_button.home_theater_remote_channel_up
      - input_button.home_theater_remote_next
      - input_button.home_theater_remote_previous
condition: []
action:
  - service: logbook.log
    metadata: {}
    data:
      name: hi
      message: |-
        {{ trigger.from_state.attributes.friendly_name|regex_replace(
          find='Home Theater Remote - ', 
          replace='') }}
    alias: Log command we're sending
  - service: remote.send_command
    metadata: {}
    data:
      command:
        - |-
          {{ trigger.from_state.attributes.friendly_name|regex_replace(
              find='Home Theater Remote - ', 
              replace='') 
          }}
    target:
      entity_id: remote.home_theater
mode: single
  ```
3. Reload the home-assistant integration on the remote & import all the "Home Theater Remote - " buttons
4. Then, you can add those to your appletv activity & use the buttons on operations that should always work (e.g. play/pause, the menu & select button, skip forward/back)

I think until we have reliable reconnection working in the appletv remote integration, this works a lot better: You still wait for the remote to wake up, but it can send the command to hass on the first try & that reliably pauses media!

**Comment by albaintor** [comment] 2024-03-01 08:05
Hi,

there is a more efficient approach (unless I missed something) : instead of input buttons + using automations, you should use scripts directly. Create one script per apple TV command, and import the scripts in the remote.
This is more efficient because you have : remote => HA script call => Apple TV Command instead of remote => event => automation trigger => Apple TV command

**Comment by albaintor** [comment] 2024-03-10 11:38
Hi,

just some thoughts for @zehnm after I checked after the code and possibilities of Home assistant : to say it shortly, we are kind of stuck because of Home assistant limitations.
Media player entities from assistant are very limited : a few playback commands, the ability to select a source or a sound mode and that is pretty much. I raised a feature request for this as I don't understand why HA does not propose additional (common) features : arrow keys and OK, back, (context) menu, number digits, and alpha keys
Also they chose to separate media player and remote entities which has not many sense as this is same device most of the time, but I think this was designed for remotes with no media player skills.
But even with this remote entity we are stuck because there are no predefined commands at all : just a custom command string as a parameter which depends on the device. 
So there is no possibility at this state to map the RC2 commands to the remote entity.
The only possibility is to design a custom text command field on the RC2 side to be transmitted to the HA remote entity when sending commands.

Also @zehnm I saw in Rust code of HA integration that you use the get states request to retrieve all the entities, am I right ?
I didn't find any other requests to do this job, which is problematic because this request does not return the link between entities : for ex usually a media player entity is linked to the remote entity through the same device or integration.
But none of these 2 links are returned

**Comment by zehnm** [comment] 2024-04-10 13:53
> just having a textbox or something where we could just copy-paste the supported commands from the Home Assistant documentation would be a great help.

With the remote-entity restrictions in HA, there won't be a list of available commands exposed in `simple_commands`. Only the on, off, toggle and generic send commands are available. The single HA `send_command` is split into a "Send command" and "Command sequence" for easier handling in the web-configurator. (More infos in https://github.com/unfoldedcircle/core-api/pull/44).

This is how it's going to look like with an Android TV Remote entity:

<img width="938" alt="image" src="https://github.com/unfoldedcircle/integration-home-assistant/assets/17356629/7ea0765f-ef36-416e-99a1-deb853d01192">

The command parameter names are still missing in the web-configurator. This will be fixed in a future update.

For the Android TV Remote entity, at least "all" keycodes can be sent (supported keycodes in Android TV is yet another sad issue though).

> I saw in Rust code of HA integration that you use the get states request to retrieve all the entities, am I right ?
I didn't find any other requests to do this job, which is problematic because this request does not return the link between entities

The [HA WebSocket API](https://developers.home-assistant.io/docs/api/websocket/) isn't that sophisticated or at least not that well documented. If I'm not mistaken, there are more calls possible which are not documented. Or it's just a feature with the generic `call_service` and one has to figure out how it works 😄 

One hacky way would be to search related devices based on the entity-id suffix and replace the prefix with `media_player`. 
For some, it would be straight forward:
<img width="546" alt="image" src="https://github.com/unfoldedcircle/integration-home-assistant/assets/17356629/f283b0b9-ead9-4a5f-8267-7916698fdfd7">

Others require a wider search filter (`media_player.office_tv` is associated to the Google Cast integration...)
<img width="546" alt="image" src="https://github.com/unfoldedcircle/integration-home-assistant/assets/17356629/c44de6eb-6b99-46a3-b474-01f2ce530dd4">

With some luck it's possible to get the related entities with the WS API, but that will require some digging.

Well, just one more reason to replace the current HA integration with a "Remote Two integration for Home Assistant" to have full configuration access and to reduce the (very) talkative `get_states` function & event subscriptions.

**Closed** 2024-04-10 17:29 UTC

**Comment by zehnm** [comment] 2024-04-11 09:25
One step closer in linking entities of the same device:
- Home Assistant WS API allows to call all kind of services. It's just not documented :-(
  Fortunately it's open source, so we can dig into the code and find all kind of goodies!
  For example the entity registry websocket functions: https://github.com/home-assistant/core/blob/2024.4.2/homeassistant/components/config/entity_registry.py#L23-L32

- Retrieve entity registry:
```json
{"type": "config/entity_registry/list", "id": 7}
```
- Response is a huge list with the complete entity registry. Filtering is not possible unfortunatately.
    Snipped of the above Office TV device with 2 entities:
```json
{
    "id": 7,
    "type": "result",
    "success": true,
    "result": [
        {
            "area_id": null,
            "config_entry_id": "1fd39c6a519c757b9362b6e80de11477",
            "device_id": "28566c0e829174e8e862fcb00727366e",
            "disabled_by": null,
            "entity_category": null,
            "entity_id": "media_player.office_tv_2",
            "platform": "androidtv_remote",
            "..."
        },
        {
            "area_id": null,
            "config_entry_id": "1fd39c6a519c757b9362b6e80de11477",
            "device_id": "28566c0e829174e8e862fcb00727366e",
            "disabled_by": null,
            "entity_category": null,
            "entity_id": "remote.office_tv",
            "platform": "androidtv_remote",
            "..."
        }
    ]
}
```

1. Retrieve data from `entity_id` with `config/entity_registry/get`
```json
{
    "type": "config/entity_registry/get",
    "entity_id": "remote.office_tv",
    "id": 10
}
```
2. Read `device_id`
3. Search related entities with `device_id`.
   This seems to require reading the full list with `config/entity_registry/list` :-( So we could already use it for step 1 and cache it.
4. Do some other magic based on `platform` value, e.g. expose Android TV Remote keycodes as simple commands for "androidtv_remote" or known Apple TV commands for "apple_tv". Ugly and sad having to do that, but would provide a much better user experience. Even better: merge it into the exposed media-player entity as simple commands, then we'd have keypad navigation and other features right in the Remote Two media player...
5. Profit!

So this would be possible, just with a bit of overhead due to missing filter options and having to deal with pretty big message responses. Going forward with a "Remote Two integration for Home Assistant" would be the better option.

**Comment by zehnm** [comment] 2024-04-11 16:39
Part of beta firmware release 1.7.10

**Comment by zehnm** [comment] 2024-04-11 16:49
Another creative way of getting the related entities of the same device: execute a template with the REST API:

```
curl --location 'http://homeassistant.local:8123/api/template' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer $TOKEN \
--data '{"template": "{{device_entities(device_id('\''remote.office_tv'\''))}}"}'
```
And back we get some non-json compatible data:
```
['media_player.office_tv_2', 'remote.office_tv']
```
But it's fragile: if the entity-id doesn't exist, the template returns some completely unrelated entities (likely the ones without a device association).

A well-typed API would be so much nicer...

**Comment by albaintor** [comment] 2024-04-12 12:14
Good catch, but indeed the websocket API is poor on hass and would need more APIs
